# Global Variables

# Fibonacci Spiral
NUM_SPIRAL_POINTS = 3500
SPIRAL_GOLDEN_ANGLE = 0.1 
SPIRAL_RADIUS_INCREMENT = 0.01

# Generation Area
GENERATION_AREA_MIN_POS = (-40,10)
GENERATION_AREA_MAX_POS = (30,40)

# Filtered Spiral
THRESHOLD_DISTANCE = 3

#Obstacles
OBST_LENGTH = 20
OBST_WIDTH = 20
OBSTACLE_HEIGHT = 25
OBST_Z = 0


DIR_GENERATED_PLOTS = "generated_tests_plot/"

DRONE_DIMENSIONS = 0.55

NUM_OBSTACLES = 2
OBST_ROTATION = 0

OBST_POS_FACTOR = 2
DRONE_FACTOR = 5