# Global Variables

# Fibonacci Spiral
NUM_SPIRAL_POINTS = 3500
SPIRAL_GOLDEN_ANGLE = 0.1 
SPIRAL_RADIUS_INCREMENT = 0.01

# Generation Area
GENERATION_AREA_MIN_POS = (-40,10)
GENERATION_AREA_MAX_POS = (30,40)

# Filtered Spiral
THRESHOLD_DISTANCE = 3 #meters
ROUND_PARAMETER = 1

#Obstacles
OBST_LENGTH = 1 #meters
OBST_WIDTH = 1 #meters 
OBSTACLE_HEIGHT = 25 #meters
OBST_Z = 0
ANGLE_STEP = 10
MAX_ATTEMPTS_GENERATION = 1000
MAX_ATTEMPTS_PERFORMANCE = 30

# Execution
MINIMUM_DISTANCE_EXECUTION = 50 # meters
LOCAL_MINIMUM = 50
DIR_GENERATED_PLOTS = "./generated_tests_plot/"
DIR_GENERATED_TESTS = "./generated_tests/"
TESTING = False
NUM_OBSTS = 2

# Obstacle Position Factor
OBST_POS_FACTOR = 2
